### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Jumoku-tree** [Jumoku-tree/protospace-37832#1]
# 本番環境URL
https://protospace-37832.herokuapp.com/

**Comment by yusuketono** [comment]
@Jumoku-tree さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できること**
削除ボタンをクリックするとエラー画面に遷移するので、削除できるように修正しましょう。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Jumoku-tree** [comment]
ありがとうございます。
修正してみたので、再度確認よろしくお願いします。

**Comment by shodai-ito** [comment]
@Jumoku-tree さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
